<a href="https://colab.research.google.com/github/maytlim/ap157/blob/main/probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
p = 0.33   #probability of getting 'heads'
N = 5     #number of times a coin would be tossed

In [2]:
import numpy as np

In [3]:
np.random.random()

0.6372001534999691

In [4]:
np.random.random(2)

array([0.24415042, 0.05032007])

In [5]:
np.random.random([3,2])

array([[0.56056484, 0.50267425],
       [0.83306865, 0.81380759],
       [0.92829647, 0.5542037 ]])

In [6]:
np.random.random([2,3,4])

array([[[0.62297166, 0.75314157, 0.69985253, 0.79871407],
        [0.70658721, 0.13387791, 0.44565668, 0.23540806],
        [0.65568182, 0.12254079, 0.15052719, 0.79310796]],

       [[0.96012866, 0.50941918, 0.59425486, 0.28567892],
        [0.01078149, 0.74442561, 0.18305657, 0.785622  ],
        [0.53380218, 0.89286856, 0.02460876, 0.48806392]]])

In [7]:
np.random.random(N)

array([0.15627929, 0.48805395, 0.01023213, 0.18726249, 0.71720323])

In [8]:
events = np.random.random(N) < p    # producing events with probability p 

In [9]:
events * 1

array([0, 0, 1, 1, 0])

In [10]:
1 - events

array([1, 1, 0, 0, 1])

In [11]:
state1 = 1
state2 = -1
states = events * state1 + (1 - events) * state2   # assigning actual states