<a href="https://colab.research.google.com/github/maytlim/ap157/blob/main/probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
p = 0.33   #probability of getting 'heads'
N = 5     #number of times a coin would be tossed

In [2]:
import numpy as np

In [3]:
np.random.random()

0.3109987124971012

In [4]:
np.random.random(2)

array([0.7036316 , 0.37683524])

In [5]:
np.random.random([3,2])

array([[0.191683  , 0.2150727 ],
       [0.63843304, 0.00579562],
       [0.13032002, 0.68299001]])

In [6]:
np.random.random([2,3,4])

array([[[0.07661898, 0.56860347, 0.29990967, 0.54356018],
        [0.90197897, 0.80370151, 0.14800316, 0.58060702],
        [0.02733747, 0.02605913, 0.24933298, 0.06243157]],

       [[0.42742371, 0.91893981, 0.5526018 , 0.62619373],
        [0.85655557, 0.50501919, 0.95402053, 0.86860183],
        [0.81308494, 0.06484211, 0.94287949, 0.93420615]]])

In [7]:
np.random.random(N)

array([0.79148782, 0.25894654, 0.90263583, 0.8139357 , 0.46787665])

In [12]:
events = np.random.random(N) < p    # producing events with probability p 
events

array([ True,  True, False, False, False])

In [13]:
events * 1

array([1, 1, 0, 0, 0])

In [14]:
1 - events

array([0, 0, 1, 1, 1])

In [16]:
state1 = 1
state2 = -1
states = events * state1 + (1 - events) * state2   # assigning actual states
states

array([ 1,  1, -1, -1, -1])